### ISSUE TITLE
Setting up -> Links lead to "not found"

### ISSUE THREAD

**Issue by policieuxjp** [vicanmendez/pluginia#2]
Hi there,
I've installed the plugin to test it on a wordpress instance, I've added my key to my profile, and the shortcode to a page with url /pluginia .
The page is showing three links : Chat / Categorias / Chats anteriores
When I click on one of them I get "Not found". A problem with the redirects ?
Any idea ?
Thanks for your help !

**Comment by miguellords** [comment]
install this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler

**Comment by policieuxjp** [comment]
Compiling c for a wordpress plugin? come on

**Comment by vicanmendez** [comment]
> Hi there, I've installed the plugin to test it on a wordpress instance, I've added my key to my profile, and the shortcode to a page with url /pluginia . The page is showing three links : Chat / Categorias / Chats anteriores When I click on one of them I get "Not found". A problem with the redirects ? Any idea ? Thanks for your help !

Hi friend! Theoretically, that links should lead to a chat with a PDF, the categories you can define for your chats, and the chat history, respectively, the project was working a few days ago, haha. Nevertheless, I have to admit this is my first WordPress plugin, the idea came from a project I was working on ASP .NET and I thought it would be a nice idea to have a WP plugin to chat with your PDFs, due to the low cost of the PHP hosting plans (and even free) if you have a WP page. 
Until the moment I was always working on WP pages but without creating plugins or themes, I was always using WP as a low code or even no code platform (sometimes I had to edit a few styles, theme parts and nothing else). 
So, as I said before this was my first WP plugin, and I am just starting with all the possibilities the plugin development can offer. May I push an old version, I would check it and maybe correct it from this night. And if you're interested on creating a WP plugin which interacts with IA, just text me, and we will see, up to the moment, it's an idea that could lead to interesting features.
Cheers!

**Comment by policieuxjp** [comment]
Hi Victor, thanks for that quick answer!
I'm exploring AI these days with a goal of having a page to chat with a group of PDFs, found chatpdf, looked for a WP plugin and finally ended up on your project.
I used to work with WP quite a bit but 10 years ago ... I feel a bit rusty (and was better at managing the team than developing myself :-) ) but I can help.

**Comment by vicanmendez** [comment]
> Hi Victor, thanks for that quick answer! I'm exploring AI these days with a goal of having a page to chat with a group of PDFs, found chatpdf, looked for a WP plugin and finally ended up on your project. I used to work with WP quite a bit but 10 years ago ... I feel a bit rusty (and was better at managing the team than developing myself :-) ) but I can help.

Hi! Good evening.. It seems the links are working now.  I think that was an issue with the branches, so I created a new one (main) with a few changes and dropped the others, I think the problem was in the branch "master". However, despite the chat is working, remember you have to be logged into your wordpress site AND have an API Key configured with chatpdf, you have to set your key in Users ---> Profile  ---> The last option will be to set your api key.
Anyway, the UI is still really poor (I almost did nothing with it) and the chat history isn't saving anything yet. I hope to fix it soon.
Cheers!

**Comment by policieuxjp** [comment]
Thanks, there was an issue on my side too and the plugin was creating problems upon activation. I think it's because you're echoing html directly from the function pluginia_menu, instead of returning the content (return $html).
